# Site settings
title: USBGuard
email: dkopecek@redhat.com

keywords: usb, usb whitelist, usb blacklist, BadUSB, security,

description: > # this means to ignore newlines until "baseurl:"
  Witty description here.

baseurl: https://dkopecek.github.io/usbguard
url: / #Leave this, change the baseurl.

header: yes
header_sm: images/banner-small.png
header_med: images/banner-med.png
header_large: images/banner-large.png
header_xl: images/banner-xl.png

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
#facebook_user:
#facebook_app_id:                      #enter your App ID
#facebook_locale: en_US
#facebook_page:                        #the URL of your Facebook Page
#facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
#twitter_user: 
#twitter_card: false
#twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
